### ISSUE TITLE
Board revision doesn't work

### ISSUE THREAD

**Issue by SchneHa** [ElektorLabs/210043-CO2-Guard#1]
Unfortunately, the new circuit board revision does not work as it is! Once it is set up, the D1 mini cannot be started and can no longer be programmed. This is because D8 is connected to the buzzer through the resistor network and T1. This pulls D8 to HIGH potential and prevents starting. If resistor R2 is disconnected from D8, it works. But then, of course, the buzzer no longer works.

I suggest connecting the cathode of LED C to D8 instead of D5. Then D5 would be free for the buzzer. However, you could also put the cathode of LED C permanently on GND, in my opinion it only has a decorative function anyway.

**Comment by lab-mathias-claussen** [comment]
Hi SchneHa, 

we will fix the Pin-assignment and move the pins arround. Also for the Buzzer it may be an idea to drive it on the low side instad of a highside drive, as this would allow for a Pull-Down. 

Best Regards

Mathias Claußen

**Comment by calm4git** [comment]
Hi,

i just created a new Pull-Request that shoudl fix the pinout and set it as following:

D1/D2 (I²C) connected to pinheader
D3/D4 RX/TX Sensor
D0 LED R
D7 LED C
D6 LED Y
D5 Buzzer
D8 LED G

**Comment by SchneHa** [comment]
Wonderful, I will order the PCBs and will do a test.

**Comment by lab-mathias-claussen** [comment]
New revision has been merged into the repository so version 2.4 can be tested
