### ISSUE TITLE
Suggestion: Change I²C-pin order to match BME280 breakout

### ISSUE THREAD

**Issue by SchneHa** [ElektorLabs/210043-CO2-Guard#3]
If you make another revision of the PCB I suggest to put the I2C pins in the right order for BME280 breakout board. That is:
VIN - GND - SCL - SDA
On last revision of PCB it is VIN - SCL - SDA - GND 

That will it make easy to connect BME280 sensor with soldered pin header to socket strips on PCB without any wires.

**Comment by lab-mathias-claussen** [comment]
Hi,

swap would be in next PCB revision. Currently no timeline is scheduled for this change.

**Comment by lab-mathias-claussen** [comment]
Thanks for submitting a fixed PCB Version. It has been merged into the main branch. Some cosemtics and text was added so the PCB is currently in Version 2.6

**Comment by SchneHa** [comment]
I already changed the PCB version text so it could be V2.5.

**Comment by lab-mathias-claussen** [comment]
As this PCB has some additional changes in it i would like to keep 2.6 as having two 2.5 versions somewhere is never a good idea in the long term.

**Comment by SchneHa** [comment]
You are right!
